### ISSUE TITLE
Add a Footer div to index.html. Include a link to a new "About" page. Possibly a "Help" page. Possibly a "Contact Us" page.

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#105]
### Expected behavior
Provide users with information about how they can use the site 
Provide some history of the site, including a link to a PDF of the Microsoft Blog post, and ???
Provide links to contact us if users have questions.
Build all this with style consistent with index.html.

### Actual behavior
None of these things exist today, other than the "Leave Feedback" button at the top.

**Comment by paulhennings** [comment]
Designers+Geeks is working on the design for this. The design should be complete by the end of October 2017.

**Comment by makfan64** [comment]
Has there been any follow up on this design?

**Comment by paulhennings** [comment]
Designers+Geeks presented their work on 10/12/2017 (https://designersandgeeks.com/events/provoke-sf-crimedata). This issue is closed and eight new issues will be opened to provide a framework for implementing this new design strategy.
