### ISSUE TITLE
As a map user, I want the Address text box to update, so that I know where I am searching.

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#107]
### Expected behavior
The Address text box at the top of the page should update to reflect the address being searched, regardless of search type.

### Actual behavior
From user feedback form: "it does not recognise data entered for address. It only does it for the given address changing the radius and period"

### Steps to reproduce
Draw a polygon. Address does not update. (bad)
Draw a rectangle. Address does not update. (bad)
Draw a circle. Address updates to match center of circle. (good)
Draw a marker. Address updates to match marker drop point. (good)

### Steps to resolve
When drawing a polygon, update the Address to match the first point drawn.
When drawing a rectangle, update the Address to match the the first point drawn.

**Comment by joeysk2012** [comment]
I will look into this.

**Comment by paulhennings** [comment]
Closed by pull #121
