### ISSUE TITLE
Develop icons for different crime incident categories

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#11]
From Tamas:

The legend should display all the pictograms for various incident types. So you will need to create a couple of marker artworks to display each type of incident.

**Comment by jasonlally** [comment]
Yes, I'm not much of a fine designer, so we may have to use Font Awesome icons, or see if we can find someone interested in developing these. In the meantime, let's just use a placeholder and we can drop in updated icons. I can look into this.

**Comment by jasonlally** [comment]
Here are the categories for reference. May be worth rolling these up into broader categories for the purposes of icons.
- ARSON
- ASSAULT
- BAD CHECKS
- BRIBERY
- BURGLARY
- DISORDERLY CONDUCT
- DRIVING UNDER THE INFLUENCE
- DRUG/NARCOTIC
- DRUNKENNESS
- EMBEZZLEMENT
- EXTORTION
- FAMILY OFFENSES
- FORGERY/COUNTERFEITING
- FRAUD
- GAMBLING
- KIDNAPPING
- LARCENY/THEFT
- LIQUOR LAWS
- LOITERING
- MISSING PERSON
- NON-CRIMINAL
- OTHER OFFENSES
- PORNOGRAPHY/OBSCENE MAT
- PROSTITUTION
- RECOVERED VEHICLE
- ROBBERY
- RUNAWAY
- SECONDARY CODES
- SEX OFFENSES, FORCIBLE
- SEX OFFENSES, NON FORCIBLE
- STOLEN PROPERTY
- SUICIDE
- SUSPICIOUS OCC
- TREA
- TRESPASS
- VANDALISM
- VEHICLE THEFT
- WARRANTS
- WEAPON LAWS

**Comment by searoutefinder** [comment]
As I see all these categories the first thing popping into my mind was to use two base categories 1. Crimes with physical injury 2. Crimes w/o physical injury and then go on with subclassing. What do you think?

**Comment by paulhennings** [comment]
Bos is looking into this.
Cross-reference with Issue #48 for a list of Clery Act reportable crimes.

**Comment by paulhennings** [comment]
The list of categories used by SFPD is too large. We need to map the SFPD categories to "Clery Category" and report on Clery Category, which is only about 10 or 12 distinct values.

This is dependent on Issue #48 being completed first, so that the "Clery Category" is available for reporting.

**Comment by joeysk2012** [comment]
I can look into this issue Paul.

Hey can we copy map icons from other crime websites or should we make them from scratch like with photoshop not sure what we can do legally. 

this site seems to have good icons already.
http://www.crimemapping.com/

**Comment by paulhennings** [comment]
We can not use crimemapping.com's icons. Their license is not an open source license and they retain all rights to their creative efforts. Ref: http://www.crimemapping.com/Home/TermsAndConditions, section 3, Licensing.

Legally, we need to build our own icons, or find some art that is in the public domain. Also, explore what Mapbox has to offer in their toolkit. This might be an area where we could consult the brigade's UX Team for some design suggestions.

Finally, don't get too hung up on the icon design. Part of the battle here will be assigning a different icon to each CSCategory, and we could just start on that with round dots or pins of various colors. We can always pursue prettier icons later and swap them in to replace our starter set of colored dots.

**Comment by joeysk2012** [comment]
Yup, okay I will just think about pins for now. I did figure out how to add custom icons from images saved in a folder path. I will upload to my repo today and show it to you this week at meetup.
