### ISSUE TITLE
Share by E-Mail URL Not Current

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#112]
### Expected behavior
When share by e-mail is clicked, the URL in the Address Bar is populated in a new e-mail message's body.

### Actual behavior
Sometimes the URL matches and sometimes it doesn't.

### Steps to reproduce
Do a variety of searches. Click Share by E-mail after each search. Compare the URL to the Address Bar in the web browser and the actual values entered on the webpage. Investigate in the code to see where the code misses updating the search URL value in the e-mail.

**Comment by yusra-ahmed-zz** [comment]
I'll do some research on this issue. Not sure yet why this is happening.
