### ISSUE TITLE
Add info window with additional information

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#13]
From Tamas:

If there is more information available on an incident let the user know by extending/changing whats displayed in the info bubble. I assume this is of minor importance, compared to the ones listed before.

**Comment by jasonlally** [comment]
I actually think this will be really useful. We already have a basic info window and it's easy enough for me to grab the appropriate pieces from the API return and format them in that window.

So, while important, it's easy enough I or someone else can pick this off. Let's not worry too much about this now.

**Comment by sarah-clements** [comment]
I'll handle this.

**Comment by paulhennings** [comment]
Remove Incident from the "bubble" and add Date. Date will be more useful to citizen users. Incident is useful to crime statisticians who will obtain Incident from the CSV download.
