### ISSUE TITLE
Adjust time selection user interaction for mobile devices

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#14]
From Tamas:

The time period selector looks weird on mobiles. I see that it is probably a plugin, but I think something simpler would still do well here.

**Comment by jasonlally** [comment]
It's definitely not suited for mobile devices. However, I do want to keep the ranges like (last quarter, last year, etc.) In user testing these kind of quick select time ranges are much easier for people than having to click around on a timeline or calendar. The plugin provides both options and is one of the nicer ones I've seen, but it's not as good on mobile.

**Comment by paulhennings** [comment]
No better options found at this time.
