### ISSUE TITLE
Investigate use of leaflet sleep for improving interactions with scrolling

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#17]
From Tamas:

There is a plugin called leaflet sleep if I remember well which pauses the map after certain seconds of inactivity. This is especially helpfule for aiding the application in better being able to be scrolled.

**Comment by jasonlally** [comment]
I think that makes sense. I've read about lots of hacks for this, but if there's already a well tested plugin, let's do that.

**Comment by paulhennings** [comment]
Please code this against the dev branch and coordinate with @rscummings to pull.
