### ISSUE TITLE
Adjust table display to be more user friendly

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#18]
From Tamas:

Let the user select which data columns they want to be displayed on mobile. In it current form the data table is not really user friendly, or not user friendly at all.

**Comment by jasonlally** [comment]
This makes sense. I don't know if folks will really use the table in the mobile use case, so fine to cinch it up. However, it's still important for individuals to be able to preview the data and download (this will happen in the desktop use case though)

**Comment by paulhennings** [comment]
Do not change the library being used for this control.
Do research the capabilities of the library and make sure we have the best possible configuration for each type of responsive device.

**Comment by paulhennings** [comment]
Table display to be revised in "Release 2.0".
