### ISSUE TITLE
Show legend based on the returned values

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#2]
There's a category field that could serve as a legend to make it a little easier to see types of crime on the map based on the query.

**Comment by jasonlally** [comment]
API docs here: https://dev.socrata.com/foundry/data.sfgov.org/cuks-n6tp

**Comment by jasonlally** [comment]
From Tamas:

Place a legend either in the map pane or outside the map. If the legend is placed inside the map into the map pane, make sure it is collapsible. This time it is probably a good idea to use https://github.com/CliffCloud/Leaflet.EasyButton to trigger the legend in a modal for example. FYI: I have an application that maps and plans sea routes based on vessel tracks (http://searoutefinder.com) and the upcoming version will use the same technique with easybutton js and a bootstrap modal.

**Comment by jasonlally** [comment]
The legend also requires the icons, I've logged that as an issue #11

**Comment by paulhennings** [comment]
This is dependent on Issue #48 being completed first, so that the "Clery Category" is available for reporting.
Also, as @jasonlally notes above, this is dependent on #11 so we have icons to display in the legend.

**Comment by joeysk2012** [comment]
I can take this on once everyone has a chance to look at my icons. I will play around with leaflet in the meantime.
