### ISSUE TITLE
Add visible "data last updated" time stamp

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/sf-crime-data#25]
People should absolutely know how fresh their data is

**Comment by jasonlally** [comment]
@hackajesse - totally agree. PD is still working on a data system migration that, when complete, will have data updated nightly with no lag, but now there's a 2 week lag on data loaded to the portal.

Regardless, transparency on the recency of the data is really important. One way to do this simply and in an automated fashion would be to make an API call to get the most recent date and time. Normally you could do a max(date) or something, but the date and time are in 2 separate fields, so you can just grab both date and time, limit 1 record and order descending.

Here's what that API call would look like: https://data.sfgov.org/resource/cuks-n6tp.json?$select=date,time&$limit=1&$order=date%20DESC,time%20DESC

Just pull the date and time out of the response json and display it to the user in a user-friendly location with user-friendly language and presto, done!
