### ISSUE TITLE
Increase limit on api returns

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#30]
Currently all API calls are using the default limit (which is 1000 records). This is fine for certain time periods, but is definitely not enough for a year or quarter's worth of data.

We can increase the call up to 50,000 records at a time. We may also have to play around with introducing paging calls depending on the use cases. Additionally, we can limit the date range a user can query, which might be a reasonable thing to do anyway. Loading millions of records into a browser can be a terrible user experience.

My current assumption is that for this application, most folks won't want to grab more than a year's worth of data at once. It might be good to understand that need from the Clery report perspective as a starting point.

More on paging and query limits here: https://dev.socrata.com/docs/paging.html

**Comment by jasonlally** [comment]
@hackajesse - can you make sure to get a sense of the timeframes people are generally pulling for Clery reports? I think the requirements are in the Act as well, but would be good to hear from university users too.

**Comment by paulhennings** [comment]
Retest after merge of #36 and #38 to assess current performance. Determine next steps on this at that time.

**Comment by jasonlally** [comment]
BTW, Socrata removed API limits so you can set the upper limit higher than 50000. You still have to send the parameter or it'll default to 1000.

**Comment by paulhennings** [comment]
Tested and retrieved "Showing 1 to 100 of 11,751 entries". This was a search for "last year" within 2320 feet of Code for America. Recent changes have resolved this issue.

**Comment by paulhennings** [comment]
Reopening this issue. The issue has come back. Queries are returning only 1000 results at this time. Need to research and re-fix.

**Comment by paulhennings** [comment]
Tested and retrieved over 1000 entries. Ready to close.
