### ISSUE TITLE
update readme with instructions on how to run locally

### ISSUE THREAD

**Issue by viinasu** [sfbrigade/sf-crime-data#34]

**Comment by paulhennings** [comment]
I got the site to run under IIS on Win7, and also using the Python SimpleHTTPServer @jasonlally pointed out on Slack. Ref: [http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python](url). Let's play around with this next Hack Night, July 13th, and then add the requested doc steps to the readme file.
