### ISSUE TITLE
As a crime statistician, I want to retrieve only those crime records that could be required by the Clery Act, so that my research time is reduced.

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#48]
Clery Act lists the following crimes:
(I) murder;
(II) sex offenses, forcible or nonforcible;
(III) robbery;
(IV) aggravated assault;
(V) burglary;
(VI) motor vehicle theft;
(VII) manslaughter;
(VIII) arson;
(IX) arrests or persons referred for campus disciplinary action for...
      liquor law violations, 
      drug-related violations, and 
      weapons possession
(ii) hate crimes
(iii) of domestic violence, 
          dating violence, and 
          stalking
Need to select distinct Category, Description and map to the above categories.
Also, need to evaluate Resolution contains "ARREST" for IX.

**Comment by paulhennings** [comment]
Cross-reference to Issue #3

**Comment by paulhennings** [comment]
### Next Steps
1. Review/Revise/Approve "Proposed_Category_Description_Resolution_Mapping_to_PossibleCleryCategory" GSheet posted to Slack.
2. Determine best coding method to add the new mapped column "PossibleCleryCategory" to the result set.
3. Add new column "PossibleCleryCategory" to queried results set. Make the new column available to the map, so the icons can vary by PossibleCleryCategory (see #11 ), so the user can filter by PossibleCleryCategory, etc. (see #3).

**Comment by joeysk2012** [comment]
Julia and I are working on this at Open data day please assign to us.
