### ISSUE TITLE
As a product owner, I want web traffic statistics reported weekly, so that we know if the site is being used.

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#50]
Ideal would be a traffic summary posted to Slack channel prj-sf-crime-data weekly on Wednesday afternoon prior to the Brigade Meetup/Hack Night.

**Comment by paulhennings** [comment]
Bumping priority on this. Hoping someone will pick it up? Applying Google Analytics or a similar monitor on the URL shouldn't be too difficult, but integrating with Slack to publish results to the team adds a nice integration challenge.

**Comment by IanThorp** [comment]
I will take a swing at this one. @paulhennings

**Comment by paulhennings** [comment]
Traffic stats are adjusted to post daily and are now reporting "real numbers".
