### ISSUE TITLE
As a crime statistician, I want to be alerted when I run a long query, so that I don't get impatient and abort before all my data is returned.

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#58]
### Expected behavior

Results from my crime search should display fairly promptly, without giving error messages. For potentially long-running searches, give me a warning to be patient and wait for the query to finish via a simple pop-up message or similar user prompt. Coach the user to tell the "unresponsive script" message to "Continue", so that all data is returned. Do this when the Radius is > 1000 feet, or the time period is greater than 90 days. 
### Actual behavior

When I search all crime within 2320 feet of 155 9th Street, SF, for "last year", the query takes a long time to finish and I am repeatedly prompted to either continue or stop an "unresponsive script". As long as I keep continuing, the query does finish and deliver all my results.

Clery Act reporting is done annually, so searches for "Last Year" should be expected.
### Steps to reproduce

Search all crime within 2320 feet of 155 9th Street, SF, for "last year".

**Comment by dtgee** [comment]
I would like to work on this one

**Comment by paulhennings** [comment]
Terrence, Go ahead and do some exploring and evaluating of options around this request. Let me know what you think would be a good design. We will hold off on actually pulling this change until we resolve the other outstanding requests and branches. Thank you!

**Comment by paulhennings** [comment]
Closing this with no work required.
Recent enhancements have the "Last Year" query running much faster and the "long running dialog script" is not appearing.
