### ISSUE TITLE
As a user, I want meaningful initial default values for Time Period, so that my search results are valid.

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#63]
### Expected behavior
On the initial page load, the "To Date" should not be any later than the "Data available through" Date.
Change the default so that the "To Date" is set equal to the "Data available through" Date.
Change the default so that the "From Date" is set equal to "Data available through" Date minus 30 days.

### Actual behavior
Dates default to "Last 30 Days"
This is misleading when results are returned, as data is generally not available for the preceding week.

### Steps to reproduce
Click http://sfcrimedata.org
Observe default dates

**Comment by steveny2k** [comment]
I can take a look at this. I am new to this project though.

**Comment by paulhennings** [comment]
Change to original request:

If "To Date" is greater than Today, change the font on the "Data available through..." message to RED, else set BLACK(default).

That should be sufficient to alert the user to the fact that data is not yet available for the time period selected (and also not give the user unexpected results for relative time periods like "Last Year" or "This Quarter").
