### ISSUE TITLE
Weekly Web Traffic Stats Missing from Slack on Jan 2

### ISSUE THREAD

**Issue by paulhennings** [sfbrigade/sf-crime-data#73]
### Expected behavior
arc.ai posts weekly web traffic statistics to slack on Monday mornings at 9:00 am PST

### Actual behavior
No traffic stats posted on Jan 2, 2017.

### Steps to reproduce
Check set up of arc.ai to see if there are any issues.
Observe behavior Jan 9.

**Comment by EvanHahn** [comment]
Do we think #75 is causing this problem?

**Comment by paulhennings** [comment]
Traffic stats are adjusted to post daily and are now reporting "real numbers".
