### ISSUE TITLE
Change radial interaction to make less confusing to the user

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#8]
From Tamas:

When an address is selected from the autocomplete, a pin and a circle representing some kind of a vicinity radius appears. I think in an enhanced version of this application, displaying a circle will not be necessary as I find it confusing as a user. Also the marker has to have some kind of a design that would emphasize that it pinpoint an address location the user has chosen.

**Comment by jasonlally** [comment]
I agree on making the marker distinct. I kind of see where you're going with removing the radius, the only thing is that for this application the radius is the only visual feedback of the area you're querying before clicking map incidents.

There may be a different approach or a better design, but I think we'll want to make it clear where people are querying in some way.

**Comment by searoutefinder** [comment]
I left the radius feature in the updated code.

**Comment by jasonlally** [comment]
Ok, yeah, that works. I'll close this one for now, we can re-open it if we really want to do something different here, but this isn't a critical change
