### ISSUE TITLE
Leave feedback form does not verify that email address is entered

### ISSUE THREAD

**Issue by OnurOzayyy** [sfbrigade/sf-crime-data#87]
### Expected behavior
The Leave Feedback form in the upper right hand corner would prompt users who do not enter any information to enter some type of data (either email address, usability feedback or comments) before proceeding to send feedback. 

### Actual behavior
When the feedback form is opened, and no fields are completed the send button still lets users submit blank data. Without requiring entry of an email address, usability feedback or comments the form proceeds to the next verification step for a captcha.

### Steps to reproduce
Clicking the Leave Feedback button, on the upper right hand side of the homepage, and proceeding to click the Send button without filling in any information.

**Comment by brianrpick** [comment]
I'd like to take this issue on
