### ISSUE TITLE
Provide ability for user to drag pin after first plotting and reverse geocode

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/sf-crime-data#9]
From Tamas:

After an address has been selected from the autocomplete, provide the ability to drag the location and refresh the address information in the autocomplete field by doing a reverse geocode using the new marker location on dragend. This would be a neat and useful feature if a user wants to slightly modify his location on the map.

**Comment by jasonlally** [comment]
I like this idea. I'd say it's on the bottom of my priority list in terms of a minimum, but certainly would be useful.

**Comment by supertask** [comment]
I'm researching the GeoJSON library. I can probably make it.

**Comment by EvanHahn** [comment]
Spent a little time looking into this. It doesnt look like [FeatureLayers](https://www.mapbox.com/mapbox.js/api/v2.1.5/l-mapbox-featurelayer/) are easily draggable...perhaps I'm mistaken.

**Comment by supertask** [comment]
I think so too. It is not easily draggable. Probably, using "mapbox-gl.js" is a easiest way to drag the pin than "mapbox.js" (the way using mapbox-gl: https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/). But the api may be significantly different. So I decided I will use "mapbox.js (2.1.5)". Here is an example to notice a drag, that I wrote. Although "userFeatureLayer" (pin) should have mouse drag functions, it doesnt have. So I implemented by force.

``` javascript
function _setDraggingMouse() {
    var isDragging = false;
    var mapComponent = mapModule.getComponents()["map"]; //map
    var userFeatureLayer = mapModule.getComponents()["layers"]["user"]; //FeatureLayer(pin)
    userFeatureLayer.on("mouseover", function(e) { isDragging = true; });
    userFeatureLayer.on("mouseout", function(e) { isDragging = false; });
    mapComponent.on("dragstart", function(e) {
        if (isDragging) { console.log("Drag pin."); }
    });
}
```

**Comment by EvanHahn** [comment]
It looks like upgrading to Mapbox.js 3.0 may also alleviate this and it seems to be an okay thing to do. That might also be an option.
